"""One-click dev startup: migrate DB → start API (new window) → open TUI.

Usage:
    .venv\\Scripts\\python.exe scripts\\dev.py

Windows only (uses CREATE_NEW_CONSOLE for the API). Stops the API when the TUI
exits. If an API is already listening on :8000 it is reused.
"""

from __future__ import annotations

import os
import secrets
import subprocess
import time
import urllib.request
from pathlib import Path

from dotenv import dotenv_values

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENV_PY = os.path.join(ROOT, ".venv", "Scripts", "python.exe")
API_URL = "http://127.0.0.1:8000"
ENV_FILE = os.path.join(ROOT, ".env")
DEV_API_KEY_VAR = "PERSONAL_AI_DEV_API_KEY"
CLI_API_KEY_VAR = "PERSONAL_AI_API_KEY"
KEY_HASH_SECRET_VAR = "PERSONAL_AI_KEY_HASH_SECRET"


def _load_env_file(env: dict) -> None:
    """Load local .env values without overriding the caller's shell."""
    if not os.path.exists(ENV_FILE):
        return
    for key, value in dotenv_values(ENV_FILE).items():
        if value is not None and key not in env:
            env[key] = value


def _append_missing_env(values: dict[str, str]) -> None:
    if not values:
        return
    path = Path(ENV_FILE)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    with path.open("a", encoding="utf-8", newline="\n") as fh:
        if existing and not existing.endswith(("\n", "\r\n")):
            fh.write("\n")
        if not existing:
            fh.write("# Local development settings generated by scripts/dev.py\n")
        else:
            fh.write("\n# Local development settings generated by scripts/dev.py\n")
        for key, value in values.items():
            fh.write(f"{key}={value}\n")


def _ensure_local_auth(env: dict) -> None:
    """Make one-click local startup usable while keeping generated keys stable."""
    if env.get("APP_ENV", "development").lower() == "production":
        return

    additions: dict[str, str] = {}
    api_key = env.get(DEV_API_KEY_VAR) or env.get(CLI_API_KEY_VAR)
    if not api_key:
        api_key = "paios-dev-" + secrets.token_urlsafe(32)
        additions[DEV_API_KEY_VAR] = api_key
        additions[CLI_API_KEY_VAR] = api_key
    else:
        if not env.get(DEV_API_KEY_VAR):
            additions[DEV_API_KEY_VAR] = api_key
        if not env.get(CLI_API_KEY_VAR):
            additions[CLI_API_KEY_VAR] = api_key

    if not env.get(KEY_HASH_SECRET_VAR):
        additions[KEY_HASH_SECRET_VAR] = "paios-hash-" + secrets.token_urlsafe(48)

    env.update(additions)
    _append_missing_env(additions)


def _env() -> dict:
    env = dict(os.environ)
    _load_env_file(env)
    _ensure_local_auth(env)
    env["PYTHONPATH"] = os.pathsep.join([ROOT, os.path.join(ROOT, "src")])
    return env


def _api_alive() -> bool:
    try:
        urllib.request.urlopen(f"{API_URL}/healthz", timeout=1)
        return True
    except Exception:  # noqa: BLE001
        return False


def _api_usable(env: dict) -> bool:
    request = urllib.request.Request(
        f"{API_URL}/v1/tools",
        headers={"X-API-Key": env[CLI_API_KEY_VAR]},
    )
    try:
        with urllib.request.urlopen(request, timeout=3) as response:
            return 200 <= response.status < 300
    except Exception:  # noqa: BLE001
        return False


def main() -> None:
    os.chdir(ROOT)
    print("=" * 60)
    print("Personal AI OS — 一键开发启动")
    print("=" * 60)
    env = _env()

    # 1. migrate the local SQLite dev DB (best-effort; fresh DBs are created by
    #    create_all on app startup, but existing DBs need the new columns).
    print("\n[1/3] 数据库迁移 (alembic upgrade head)…")
    db_file = os.path.join("data", "app.db")
    env["DATABASE_URL"] = f"sqlite+aiosqlite:///{db_file}"
    try:
        subprocess.run(
            [VENV_PY, "-m", "alembic", "upgrade", "head"],
            cwd=ROOT, env=env, check=False,
        )
    except Exception as exc:  # noqa: BLE001
        print(f"    迁移失败（可忽略，若为全新库）: {exc}")

    # 2. start the API in its own console window.
    api: subprocess.Popen | None = None
    if _api_alive():
        if not _api_usable(env):
            print(
                "    API 已在 :8000 运行，但不接受当前本地开发密钥；"
                "请先关闭旧 API 窗口后重新运行本脚本。"
            )
            raise SystemExit(1)
        print("    API 已在运行，复用现有实例。")
    else:
        print(f"\n[2/3] 启动 API 服务 → {API_URL}（新窗口）…")
        api = subprocess.Popen(
            [VENV_PY, "-m", "apps.api.main"],
            cwd=ROOT, env=env,
            creationflags=getattr(subprocess, "CREATE_NEW_CONSOLE", 0),
        )
        print("    等待服务就绪…")
        for _ in range(90):
            if _api_alive():
                break
            time.sleep(1)
        if not _api_alive():
            print("    API 未在预期时间内就绪，请查看 API 窗口输出。")
        elif not _api_usable(env):
            print("    API 已启动但鉴权检查失败，请查看 API 窗口输出。")
            if api is not None and api.poll() is None:
                api.terminate()
            raise SystemExit(1)

    # 3. open the interactive TUI in this window.
    print("\n[3/3] 启动交互 TUI（输入 Ctrl+C 退出）…\n")
    tui = [os.path.join(ROOT, ".venv", "Scripts", "personal-ai.exe")]
    if not os.path.exists(tui[0]):
        tui = [VENV_PY, "-m", "apps.cli.main"]
    try:
        subprocess.call(tui, cwd=ROOT, env=env)
    except KeyboardInterrupt:
        pass
    finally:
        if api is not None and api.poll() is None:
            api.terminate()
        print("\n已退出。API 服务已停止。")


if __name__ == "__main__":
    main()
