"""One-click dev startup: migrate DB → start API → open TUI.

Usage:
    uv run python scripts/dev.py

On Windows, the API opens in a new console. On macOS and Linux, it runs as a
child process in the current terminal. The API stops when the TUI exits. If an
API is already listening on :8000 it is reused.
"""

from __future__ import annotations

import os
import secrets
import shutil
import subprocess
import time
import urllib.request
from pathlib import Path

from dotenv import dotenv_values

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_FILE = os.path.join(ROOT, ".env")
DEV_API_KEY_VAR = "PERSONAL_AI_DEV_API_KEY"
CLI_API_KEY_VAR = "PERSONAL_AI_API_KEY"
KEY_HASH_SECRET_VAR = "PERSONAL_AI_KEY_HASH_SECRET"


def _python_command() -> list[str]:
    """Return the project Python command for the current platform."""
    if shutil.which("uv"):
        return ["uv", "run", "python"]

    venv_dir = "Scripts" if os.name == "nt" else "bin"
    python_name = "python.exe" if os.name == "nt" else "python"
    venv_python = os.path.join(ROOT, ".venv", venv_dir, python_name)
    if os.path.exists(venv_python):
        return [venv_python]

    raise RuntimeError("找不到 uv 或项目虚拟环境；请先安装 uv 并执行 `uv sync --extra dev`。")


def _load_env_file(env: dict) -> None:
    """Load local .env values without overriding the caller's shell."""
    if not os.path.exists(ENV_FILE):
        return
    for key, value in dotenv_values(ENV_FILE).items():
        if value is not None and key not in env:
            env[key] = value


def _append_missing_env(values: dict[str, str]) -> None:
    if not values:
        return
    path = Path(ENV_FILE)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    with path.open("a", encoding="utf-8", newline="\n") as fh:
        if existing and not existing.endswith(("\n", "\r\n")):
            fh.write("\n")
        if not existing:
            fh.write("# Local development settings generated by scripts/dev.py\n")
        else:
            fh.write("\n# Local development settings generated by scripts/dev.py\n")
        for key, value in values.items():
            fh.write(f"{key}={value}\n")


def _ensure_local_auth(env: dict) -> None:
    """Make one-click local startup usable while keeping generated keys stable."""
    if env.get("APP_ENV", "development").lower() == "production":
        return

    additions: dict[str, str] = {}
    api_key = env.get(DEV_API_KEY_VAR) or env.get(CLI_API_KEY_VAR)
    if not api_key:
        api_key = "paios-dev-" + secrets.token_urlsafe(32)
        additions[DEV_API_KEY_VAR] = api_key
        additions[CLI_API_KEY_VAR] = api_key
    else:
        if not env.get(DEV_API_KEY_VAR):
            additions[DEV_API_KEY_VAR] = api_key
        if not env.get(CLI_API_KEY_VAR):
            additions[CLI_API_KEY_VAR] = api_key

    if not env.get(KEY_HASH_SECRET_VAR):
        additions[KEY_HASH_SECRET_VAR] = "paios-hash-" + secrets.token_urlsafe(48)

    env.update(additions)
    _append_missing_env(additions)


def _env() -> dict:
    env = dict(os.environ)
    _load_env_file(env)
    _ensure_local_auth(env)
    env["PYTHONPATH"] = os.pathsep.join([ROOT, os.path.join(ROOT, "src")])
    return env


def _api_url(env: dict) -> str:
    """Return the local API URL from the server's configured port."""
    port = int(env.get("PERSONAL_AI_PORT", "8000"))
    return f"http://127.0.0.1:{port}"


def _api_alive(api_url: str) -> bool:
    try:
        urllib.request.urlopen(f"{api_url}/healthz", timeout=1)
        return True
    except Exception:  # noqa: BLE001
        return False


def _api_usable(api_url: str, env: dict) -> bool:
    request = urllib.request.Request(
        f"{api_url}/v1/tools",
        headers={"X-API-Key": env[CLI_API_KEY_VAR]},
    )
    try:
        with urllib.request.urlopen(request, timeout=3) as response:
            return 200 <= response.status < 300
    except Exception:  # noqa: BLE001
        return False


def main() -> None:
    os.chdir(ROOT)
    print("=" * 60)
    print("Personal AI OS — 一键开发启动")
    print("=" * 60)
    env = _env()
    python = _python_command()
    api_url = _api_url(env)
    env["PERSONAL_AI_API_URL"] = api_url

    # 1. migrate the local SQLite dev DB (best-effort; fresh DBs are created by
    #    create_all on app startup, but existing DBs need the new columns).
    print("\n[1/3] 数据库迁移 (alembic upgrade head)…")
    db_file = os.path.join("data", "app.db")
    env["DATABASE_URL"] = f"sqlite+aiosqlite:///{db_file}"
    try:
        subprocess.run(
            [*python, "-m", "alembic", "upgrade", "head"],
            cwd=ROOT, env=env, check=False,
        )
    except Exception as exc:  # noqa: BLE001
        print(f"    迁移失败（可忽略，若为全新库）: {exc}")

    # 2. Windows opens the API in its own console; other platforms use a child process.
    api: subprocess.Popen | None = None
    if _api_alive(api_url):
        if not _api_usable(api_url, env):
            print(
                f"    API 已在 {api_url} 运行，但不接受当前本地开发密钥；"
                "请先关闭旧 API 窗口后重新运行本脚本。"
            )
            raise SystemExit(1)
        print("    API 已在运行，复用现有实例。")
    else:
        print(f"\n[2/3] 启动 API 服务 → {api_url}…")
        api = subprocess.Popen(
            [*python, "-m", "apps.api.main"],
            cwd=ROOT, env=env,
            creationflags=getattr(subprocess, "CREATE_NEW_CONSOLE", 0),
        )
        print("    等待服务就绪…")
        for _ in range(90):
            if _api_alive(api_url):
                break
            if api.poll() is not None:
                print(
                    f"    API 在监听 {api_url} 前退出（退出码 {api.returncode}）。"
                    "端口可能已被其他进程占用。"
                )
                raise SystemExit(1)
            time.sleep(1)
        if not _api_alive(api_url):
            print("    API 未在预期时间内就绪，请查看 API 窗口输出。")
            if api.poll() is None:
                api.terminate()
            raise SystemExit(1)
        if not _api_usable(api_url, env):
            print("    API 已启动但鉴权检查失败，请查看 API 窗口输出。")
            if api is not None and api.poll() is None:
                api.terminate()
            raise SystemExit(1)

    # 3. open the interactive TUI in this window.
    print("\n[3/3] 启动交互 TUI（输入 Ctrl+C 退出）…\n")
    tui = [*python, "-m", "apps.cli.main"]
    try:
        subprocess.call(tui, cwd=ROOT, env=env)
    except KeyboardInterrupt:
        pass
    finally:
        if api is not None and api.poll() is None:
            api.terminate()
        print("\n已退出。API 服务已停止。")


if __name__ == "__main__":
    main()
